
// CALLED ROOT LAYOUT

export const metadata = {
  title: {
    default: "Create Next App",
    template: "%s | Create Next App",
  
  },
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
      >
        <header style={{backgroundColor:"yellow", padding:"2px"}}>Navbar</header>
        {children}
        <footer style={{backgroundColor:"blue", padding:"2px", marginTop:"5px"}}>Footer</footer>
      </body>
    </html>
  );
}
